export interface GlobeClient {
  id: string
  name: string
  city: string
  country: string
  coords: [number, number] // [longitude, latitude]
  region: 'North America' | 'Europe' | 'Asia'
  service: string
  deliverable: string
  summary: string
  quote?: string
  clientRole?: string
  metric?: { value: string; label: string }
  url?: string
  logo?: string
}

export const GLOBE_CLIENTS: GlobeClient[] = [
  {
    id: 'simpli-home',
    name: 'Simpli Home',
    city: 'Toronto',
    country: 'Canada',
    coords: [-79.3832, 43.6532],
    region: 'North America',
    service: 'AI Automation / Media Ops',
    deliverable: 'Figma Buzz pipeline automation',
    summary: 'Automated bulk product visual generation and resizing pipeline.',
    metric: { value: '11 hrs', label: 'Saved per week' },
    quote: 'Our team finally does the work we hired them for. Game changer.',
    clientRole: 'Darcy McGilvery',
    url: '/work/simpli-home',
    logo: '/client-logos/simpli-home.svg',
  },
  {
    id: 'sustainable-btc',
    name: 'Sustainable Bitcoin Protocol',
    city: 'Zurich / New York',
    country: 'Switzerland / USA',
    coords: [-74.006, 40.7128],
    region: 'North America',
    service: 'UI/UX Design & Design System',
    deliverable: 'Institutional protocol interface',
    summary: 'Scalable UX architecture and design foundation for institutional crypto users.',
    metric: { value: '3+ yrs', label: 'Active partnership' },
    quote: 'They shaped our entire digital appearance from the ground up and are still the first people we call.',
    clientRole: 'Co-founder',
    url: '/work/sustainable-bitcoin-protocol',
    logo: '/client-logos/sustainable-bitcoin-protocol.svg',
  },
  {
    id: 'ap-cleanco',
    name: 'AP Cleanco',
    city: 'Manchester',
    country: 'United Kingdom',
    coords: [-2.2426, 53.4808],
    region: 'Europe',
    service: 'Web Development & Local SEO',
    deliverable: 'Next.js commercial marketing platform',
    summary: 'Commercial service platform with sub-second loads and local search visibility.',
    metric: { value: '3 weeks', label: 'Concept to launch' },
    quote: 'Fastest turnaround we had. Quality was better than agencies charging 5x.',
    clientRole: 'Co-founder',
    url: '/work/ap-cleanco',
    logo: '/client-logos/ap-cleanco.svg',
  },
  {
    id: 'archmodal',
    name: 'Archmodal',
    city: 'Los Angeles',
    country: 'United States',
    coords: [-118.2437, 34.0522],
    region: 'North America',
    service: 'UI/UX & Web Development',
    deliverable: 'Architectural studio web platform',
    summary: 'Portfolio presentation engineered for 3D modeling and architectural classrooms.',
    quote: 'Team was timely, design was great and they did above and beyond my request.',
    clientRole: 'Stacey Bae, Developer',
    url: 'https://www.archmodal.com/',
    logo: '/client-logos/archmodal.svg',
  },
  {
    id: 'cozmo-realty',
    name: 'Cozmo Realty',
    city: 'Dallas',
    country: 'United States',
    coords: [-96.797, 32.7767],
    region: 'North America',
    service: 'Full-Stack Web Engineering',
    deliverable: 'Property portal & lead workflows',
    summary: 'Custom digital real estate workflows with intuitive search filters.',
    quote: 'Even if I do not explain the design I want, they know exactly what style to build.',
    clientRole: 'Sang Hyun Han, Full Stack Engineer',
    logo: '/client-logos/cozmo-realty.svg',
  },
  {
    id: 'champion-lenders',
    name: 'Champion Lenders',
    city: 'Chicago',
    country: 'United States',
    coords: [-87.6298, 41.8781],
    region: 'North America',
    service: 'Fintech Web Design & Prototyping',
    deliverable: 'Conversion-focused lending interface',
    summary: 'Clear lending rates presentation and fast inquiry intake flow.',
    quote: 'Always responded quickly and has a really good sense of design.',
    clientRole: 'John Kim, CEO',
    logo: '/client-logos/champion-lenders.svg',
  },
  {
    id: 'elevagechiotspug',
    name: 'Elevagechiotspug',
    city: 'Montreal',
    country: 'Canada',
    coords: [-73.5673, 45.5017],
    region: 'North America',
    service: 'Boutique Web & Brand Styling',
    deliverable: 'High-touch customer journey',
    summary: 'Tailored aesthetic presentation with structured enquiry handling.',
    quote: 'They understood exactly what I wanted and gave it to me. Very stylish designs.',
    clientRole: 'Benoit Marcell, Owner',
  },
  {
    id: 'tocal',
    name: 'Tocal (DbyT Dynamics)',
    city: 'Pune',
    country: 'India',
    coords: [73.8567, 18.5204],
    region: 'Asia',
    service: 'Hardware Product Web Experience',
    deliverable: 'Next.js product architecture',
    summary: 'Clean, modern showcase for smart controller hardware and firmware ecosystem.',
    url: 'https://tocal.in/',
    logo: '/client-logos/tocal.svg',
  },
  {
    id: 'earth-by-blancora',
    name: 'Earth by Blancora',
    city: 'Mumbai',
    country: 'India',
    coords: [72.8777, 19.076],
    region: 'Asia',
    service: 'E-Commerce Architecture',
    deliverable: 'Sustainable apparel storefront',
    summary: 'High-converting mobile storefront with quick checkout and brand editorial.',
    url: 'https://blancoraclothing.com/shop',
    logo: '/client-logos/blancora.svg',
  },
  {
    id: 'katalyst-consulting',
    name: 'Katalyst Consulting',
    city: 'New Delhi',
    country: 'India',
    coords: [77.209, 28.6139],
    region: 'Asia',
    service: 'Corporate Authority Web Presence',
    deliverable: 'Advisory firm web architecture',
    summary: 'Positioning and information structure for institutional management consulting.',
    url: 'https://www.katalystcs.co.in/',
    logo: '/client-logos/katalyst.png',
  },
  {
    id: 'jaxl',
    name: 'JAXL',
    city: 'Bengaluru',
    country: 'India',
    coords: [77.5946, 12.9716],
    region: 'Asia',
    service: 'Frontend Engineering & Prototyping',
    deliverable: 'CSS3 / HTML5 / SVG system',
    summary: 'Interactive technical interfaces programmed for high responsiveness.',
    quote: 'Quickly prototyped the design I had in mind and programmed it using modern web tech.',
    clientRole: 'Abhinav Singh, Co-founder',
  },
  {
    id: 'metathumbz',
    name: 'MetaThumbz',
    city: 'Pune',
    country: 'India',
    coords: [73.9, 18.55],
    region: 'Asia',
    service: 'Web Development & Custom Systems',
    deliverable: 'Production web development',
    summary: 'Personal attention to front-end and full-stack technical details.',
    quote: 'One of the best web development services out there. Personal attention to the smallest details.',
    clientRole: 'Rudra Ghodke, Founder',
  },
]
