import type { Metadata } from 'next'
import { LegalPageLayout } from '@/components/legal/LegalPageLayout'

export const metadata: Metadata = {
  title: 'Privacy Policy | WebsiteVikreta',
  description: 'Learn how WebsiteVikreta collects, uses, stores, and protects your personal information and your privacy rights.',
  keywords: [
    'WebsiteVikreta privacy policy',
    'data privacy',
    'GDPR',
    'CCPA',
    'personal data policy',
  ],
  openGraph: {
    title: 'Privacy Policy | WebsiteVikreta',
    description: 'Learn how WebsiteVikreta collects, uses, stores, and protects your personal information and your privacy rights.',
    url: 'https://stage.websitevikreta.com/legal/privacy-policy',
    siteName: 'WebsiteVikreta',
    type: 'website',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'WebsiteVikreta Privacy Policy',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Privacy Policy | WebsiteVikreta',
    description: 'Learn how WebsiteVikreta collects, uses, stores, and protects your personal information and your privacy rights.',
    images: ['/og-image.png'],
  },
  alternates: {
    canonical: 'https://stage.websitevikreta.com/legal/privacy-policy',
  },
  robots: {
    index: true,
    follow: false,
  },
}

const sections = [
  {
    heading: 'Introduction',
    content: 'Welcome to Website Vikreta. Website Vikreta ("us", "we", or "our") operates WebsiteVikreta.com (hereinafter referred to as "Service"). Our Privacy Policy governs your visit to WebsiteVikreta.com, and explains how we collect, safeguard and disclose information that results from your use of our Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").',
  },
  {
    heading: 'Definitions',
    content: [
      'SERVICE means the WebsiteVikreta.com website operated by Website Vikreta.',
      'PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).',
      'USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).',
      'COOKIES are small files stored on your device (computer or mobile device).',
      'DATA CONTROLLER means a natural or legal person who determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.',
      'DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller.',
      'DATA SUBJECT is any living individual who is the subject of Personal Data.',
      'THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.',
    ],
  },
  {
    heading: 'Information Collection and Use',
    content: 'We collect several different types of information for various purposes to provide and improve our Service to you.',
  },
  {
    heading: 'Types of Data Collected',
    content: [
      'Personal Data: While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include email address, first name and last name, phone number, address, country, state, ZIP/Postal code, city, and cookies and usage data.',
      'Usage Data: We may collect information that your browser sends whenever you visit our Service. This may include your IP address, browser type, browser version, pages visited, time and date of visit, time spent on pages, and other diagnostic data.',
      'Tracking Cookies Data: We use cookies and similar tracking technologies to track activity on our Service. Types include Session Cookies, Preference Cookies, Security Cookies, and Advertising Cookies.',
      'Other Data: We may also collect information such as age, date of birth, place of birth, citizenship, telephone number, and other relevant data while using our Service.',
    ],
  },
  {
    heading: 'Use of Data',
    content: [
      'To provide and maintain our Service.',
      'To notify you about changes to our Service.',
      'To allow you to participate in interactive features of our Service when you choose to do so.',
      'To provide customer support.',
      'To gather analysis or valuable information so that we can improve our Service.',
      'To monitor the usage of our Service.',
      'To detect, prevent and address technical issues.',
      'To fulfil any other purpose for which you provide it.',
      'To carry out our obligations and enforce our rights arising from any contracts entered into between you and us.',
      'To provide you with notices about your account and/or subscription.',
      'To provide you with news, special offers and general information about other goods and services we offer.',
      'For any other purpose with your consent.',
    ],
  },
  {
    heading: 'Retention of Data',
    content: 'We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies. Usage Data is generally retained for a shorter period, except when used to strengthen security or improve functionality.',
  },
  {
    heading: 'Transfer of Data',
    content: 'Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where data protection laws may differ. If you are located outside India and choose to provide information to us, please note that we transfer the data to India and process it there. Website Vikreta will take all steps reasonably necessary to ensure your data is treated securely and in accordance with this Privacy Policy.',
  },
  {
    heading: 'Disclosure of Data',
    content: [
      'Disclosure for Law Enforcement: Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.',
      'Business Transaction: If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.',
      'Other cases: To our subsidiaries and affiliates; to contractors and service providers; to fulfill the purpose for which you provide it; for including your company\'s logo on our website; with your consent; or to protect the rights, property, or safety of the Company, our customers, or others.',
    ],
  },
  {
    heading: 'Security of Data',
    content: 'The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.',
  },
  {
    heading: 'Your Data Protection Rights Under GDPR',
    content: [
      'If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights covered by GDPR.',
      'The right to access, update or to delete the information we have on you.',
      'The right of rectification — to have your information corrected if inaccurate or incomplete.',
      'The right to object to our processing of your Personal Data.',
      'The right of restriction — to request that we restrict the processing of your personal information.',
      'The right to data portability — to receive a copy of your Personal Data in a structured, machine-readable format.',
      'The right to withdraw consent at any time where we rely on your consent to process your personal information.',
      'To exercise these rights, please email us at contact@websitevikreta.com.',
    ],
  },
  {
    heading: 'Your Data Protection Rights Under CalOPPA',
    content: [
      'Users can visit our site anonymously.',
      'Our Privacy Policy link includes the word \'Privacy\' and can easily be found on the home page.',
      'Users will be notified of any privacy policy changes on our Privacy Policy page.',
      'Users are able to change their personal information by emailing us at contact@websitevikreta.com.',
      'We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place.',
    ],
  },
  {
    heading: 'Your Data Protection Rights Under CCPA',
    content: [
      'If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell it.',
      'You may request: the categories of personal information we have collected; the sources from which we collect it; the business purpose for collecting it; the categories of third parties with whom we share it; and the specific pieces of personal information collected about you.',
      'You may request deletion of your personal information. We will delete the information we hold as of the date of your request.',
      'We don\'t sell or rent your personal information to any third parties for any purpose.',
      'To exercise your California data protection rights, please email: contact@websitevikreta.com.',
    ],
  },
  {
    heading: 'Service Providers',
    content: 'We may employ third party companies and individuals to facilitate our Service, provide Service on our behalf, perform Service-related services, or assist us in analysing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.',
  },
  {
    heading: 'Analytics, CI/CD Tools and Remarketing',
    content: 'We may use third-party Service Providers to monitor and analyze the use of our Service, to automate the development process, and to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.',
  },
  {
    heading: 'Payments',
    content: 'We may provide paid products and/or services within our Service. We use third-party services for payment processing. We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to PCI-DSS standards.',
  },
  {
    heading: 'Links to Other Sites',
    content: 'Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party\'s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
  },
  {
    heading: "Children's Privacy",
    content: 'Our Services are not intended for use by children under the age of 18. We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.',
  },
  {
    heading: 'Changes to This Privacy Policy',
    content: 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the effective date at the top. You are advised to review this Privacy Policy periodically for any changes.',
  },
  {
    heading: 'Contact Us',
    content: 'If you have any questions about this Privacy Policy, please contact us by email: contact@websitevikreta.com.',
  },
]

export default function PrivacyPolicyPage() {
  return (
    <LegalPageLayout
      title="Privacy Policy"
      lastUpdated="August 19, 2020"
      sections={sections}
    />
  )
}
